### PR TITLE
Extend loopback workaround

### LINKED ISSUE #135: Loopback is incomplete
The following scenarios exist for client -> server within the same host:

(Only Tcp is shown, but we need to handle it for Udp as well)
```
// bind | connect

// 0s | 127.0.0.1
// client: local Ok(127.0.0.1:49582), peer Ok(127.0.0.1:1234)
// server: 127.0.0.1:49582, local Ok(127.0.0.1:1234), peer Ok(127.0.0.1:49582)

// 127.0.0.1 | 127.0.0.1
// client: local Ok(127.0.0.1:49622), peer Ok(127.0.0.1:1234)
// server: 127.0.0.1:49622, local Ok(127.0.0.1:1234), peer Ok(127.0.0.1:49622)

// 0s | 192.168.1.42
// client: local Ok(192.168.1.42:49716), peer Ok(192.168.1.42:1234)
// server: 192.168.1.42:49716, local Ok(192.168.1.42:1234), peer Ok(192.168.1.42:49716)

// 127.0.0.1 | 192.168.1.42
// Error: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }
```

The first two work as expected, including setting the correct `local|peer_addr` on each side of the stream. The last two cause panics today due to holes in the stop-gap implementation for loopback.

We need to address this with workarounds and/or include this in the refactor being discussed in #132 .

### PR DESCRIPTION
**Pull request by jeremymill**
This should resolve #135.

Current workaround for loopback from #118 does not allow connecting to the same host when using the public ip. This change extends the workaround to allow for that, unblocking additional use cases pending a larger rework to fully support multiple interfaces (see #132)

### CODE REVIEW

File: src/net/tcp/stream.rs [hunk 1]
```diff
@@ -74,7 +74,7 @@ impl TcpStream {
             let rx = host.tcp.new_stream(pair);
 
             let syn = Protocol::Tcp(Segment::Syn(Syn { ack }));
-            if !dst.ip().is_loopback() {
+            if !dst.ip().is_loopback() && dst.ip() != local_addr.ip() {
```
Comment (atreyas) [inline src/net/tcp/stream.rs:77]: Maybe introduce a function that can compare the host for 2 IPs.

**Review by mh32 — APPROVED** [review]

File: src/host.rs [hunk 2]
```diff
@@ -417,6 +417,11 @@ pub fn matches(bind: SocketAddr, dst: SocketAddr) -> bool {
     bind == dst
 }
 
+/// Returns whether loopback is supported from src to dst
```
Comment (atreyas) [inline src/host.rs:420]: Technically this is not a loopback. It ends up behaving like loopback because of how turmoil is routing to the local IP address. Mayeb `is_same`?

File: tests/tcp.rs [hunk 3]
```diff
@@ -830,6 +832,38 @@ fn loopback_to_localhost_v4() -> Result {
     run_localhost_test(IpVersion::V4, bind_addr, connect_addr)
 }
 
+#[test]
+fn loopback_wildcard_public_v4() -> Result {
+    let bind_addr = SocketAddr::new(Ipv4Addr::UNSPECIFIED.into(), 1234);
+    let connect_addr = SocketAddr::from((Ipv4Addr::new(192, 168, 0, 1), 1234));
+    run_localhost_test(IpVersion::V4, bind_addr, connect_addr)
```
Comment (mcches) [inline tests/tcp.rs:839]: Does this verify the stream's addrs are set the same as what tokio::net types return? These need to behave the same way.

**Review by mcches — COMMENTED** [review]
Thanks for picking up this issue. I left one comment.

File: tests/tcp.rs (hunk 3 above)
Comment (jeremymill) [reply tests/tcp.rs:839]: `run_localhost_test` asserts:

```
assert_eq!(socket.local_addr()?.ip(), connect_addr.ip());
assert_eq!(socket.peer_addr()?.ip(), connect_addr.ip());
```

on both server and client.
